206 Partial Content
Content-Type: video/mp4
Last-Modified: Mon, 25 Aug 2025 14:34:03 GMT
Date: Mon, 25 Aug 2025 16:14:46 GMT
Content-Length: 833085310
ETag: "59486a37c2a2f472ea8261ca9a8c39bb"
Accept-Ranges: bytes
Content-Range: bytes 0-833085309/833085310
x-amz-id-2: Sje9J5f89MxkyAF7sYuWYGNBqEWOQJ7wfPzUJX0/6eT5/s9fDtN3mqvZLXo17E7caAaFmkaYpQWTmtVi3ximsAIVxjg+f4JoookwLYxnna8=
x-amz-server-side-encryption: AES256
x-amz-replication-status: COMPLETED
Server: AmazonS3
x-amz-version-id: xPuHBFQmQjGgIzIFb3AyxcARQgNsuRCG
x-amz-request-id: D55NVMBDZ1ETQ1HC
