206 Partial Content
Content-Type: video/mp4
Last-Modified: Mon, 25 Aug 2025 14:34:03 GMT
Date: Mon, 25 Aug 2025 16:14:47 GMT
Content-Length: 832167806
ETag: "59486a37c2a2f472ea8261ca9a8c39bb"
Accept-Ranges: bytes
Content-Range: bytes 917504-833085309/833085310
x-amz-id-2: JthTlWNhLU1+I1x09bB2P8ZavVUHoToIZv56nOWp/8RP5F1jnC4r/h5EAr/mAJ7E4FGw215hZLflHg1YfPYvgrt/wRDktCOlNB20MWoHpQ0=
x-amz-server-side-encryption: AES256
x-amz-replication-status: COMPLETED
Server: AmazonS3
x-amz-version-id: xPuHBFQmQjGgIzIFb3AyxcARQgNsuRCG
x-amz-request-id: QAPKWVC8HBCG4PDT
